services:
  - type: web
    name: springboot-app
    runtime: java
    plan: free
    buildCommand: "./mvnw clean package"
    startCommand: "java -jar target/ERPWebApp-0.0.1-SNAPSHOT.jar --server.port=8080 --server.address=0.0.0.0"
    envVars:
      - key: PORT
        value: "8080"
      - key: JAVA_OPTS
        value: "-Dserver.port=8080 -Dserver.address=0.0.0.0"