services:
  - type: web
    name: erp-web-service
    env: docker
    buildCommand: "./mvnw clean package"
    startCommand: "java -jar target/*.jar"
    plan: free
    envVars:
      - key: JAVA_HOME
        value: "/opt/render/project/.render/jdk"
      - key: JDK_VERSION
        value: "17"
      - key: RENDER_SKIP_AUTODETECT
        value: "true"
