name: Keep Render Active

on:
  schedule:
    - cron: '*/5 * * * *' # Runs every 5 minutes

jobs:
  keep_alive:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render Service
        run: curl -s https://erpwebservice.onrender.com > /dev/null